### PR TITLE
Add Slack hooks following hipchat structure

### PR DESCRIPTION
**Pull request by Sikian**
Please change the icon_url and provide any feedback if necessary.

### CODE REVIEW

**Comment by joshuarudd** [comment]
Hey @Sikian, thanks for submitting this. We’ll check it out soon!

**Comment by Sikian** [comment]
Any news, @joshuarudd ?

**Comment by joshuarudd** [comment]
@Sikian it’s in our Engineering team’s queue to set up and test.

**Comment by Sikian** [comment]
Another week gone by. Any news @joshuarudd ?

**Comment by joshuarudd** [comment]
@Sikian it’s currently in one of our dev’s queue. We’ll let you know once it’s tested!

**Comment by Sikian** [comment]
Disappointing

**Comment by ncornag** [comment]
Hey, we are almost there! Patience! :smile:

**Comment by joshuarudd** [comment]
Hey @Sikian, thanks for submitting this pull request. We’ve tested it and soft-launched it for all customers. I’m planning to update the related idea soon (http://feedback.uservoice.com/forums/1/suggestions/5300757) – would you like me to give you credit in the status update for building it?

**Comment by danielpennypacker** [comment]
Hey, sorry for the delay getting it on there, I'm new at UserVoice, and it took me a little while to get up to speed :) 

Great code, didn't have to change anything, thanks so much!

**Comment by Sikian** [comment]
@danielpennypacker it's ok :)

@joshuarudd That would be great, thanks!

**Pull request merged**
